### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [eranpeer/FakeIt#129]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by helmesjo** [comment]
I guess this should be closed.

**Comment by helmesjo** [comment]
Related: https://github.com/conan-io/conan-center-index/pull/4992

**Comment by FranckRJ** [comment]
It's available in conan center now : https://conan.io/center/fakeit
