### ISSUE TITLE
Mocking classes that exceed 50 virtual abstract methods segafults in runtime

### ISSUE THREAD

**Issue by achary** [eranpeer/FakeIt#13]
In such case, the Access Violation exception is thrown at:
VTUtils.hpp:33

Environment: Windows 7 
Compilers:
VS 2013 (64 bit) 
as well as 
gcc (i686-posix-dwarf-rev2, Built by MinGW-W64 project) 4.9.1

**Comment by eranpeer** [comment]
Solved!!
The limit now is 1000 (I guess this is more than enough).
Please note that due to implementation constraints there will always be a limit of how many virtual methods FakeIt can handle in one single mock class.

**Comment by achary** [comment]
Superb, thanks.
A 1000 seems is truely good enought for me. 
(although I work in with range of 400 rather frequently).

**Comment by eranpeer** [comment]
Hi,
I've just noticed that you added an "include" section to the quickstart.
Thanks for your help.
I've changed the section a little. The only file you have to include is:
fakeit.hpp

**Comment by achary** [comment]
oh, I see. thanks.
no problem at all.
for some reasons I wasn't sure and the two above was the way I found
working...

Anyway. FakeIt seems doing very good job in my opinion. The fact that there
is no so much code generation for pure mocking (that's really a winning
point to me in comparison to gmock for example) is just great!

And the syntax of instantiating mock from pure abstract class right in the
test case - just sweet.

I'm really impressed and I personally think it's one of greatest mocking
lib for C++ out there.

I've noticed that stubbing generates pretty lot of code and large binaries
(at least when you oscillate in ranges of hundreds to 1000 methods to stub).

Could that potentially be elimintated? E.g. by assuming some no-action
default stubbing for "void foo(...)" like methods and e.g. returning
default values in case of non-void return value types?.

cheers,
Adam


2015-02-25 12:11 GMT+00:00 eranpeer <notifications@github.com>:

> Hi,
> I've just noticed that you added an "include" section to the quickstart.
> Thanks for your help.
> I've changed the section a little. The only file you have to include is:
> fakeit.hpp
> On Feb 24, 2015 1:33 AM, "achary" <notifications@github.com> wrote:
>
> > Superb, thanks.
> > A 1000 seems is truely good enought for me.
> > (although I work in with range of 400 rather frequently).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/eranpeer/FakeIt/issues/13#issuecomment-75661705>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eranpeer/FakeIt/issues/13#issuecomment-75949802>.
>



-- 
Adam Charytoniuk

**Comment by eranpeer** [comment]
I noticed that on MinGW64 the executable is extremely big (twice the size
of gcc and 20 times the size of VS2013) and link time on MinGW is very long
compared to gcc and VS.
The size of the executable will be in the focus on the next several minor
releases. I hope I will be able to reduce it significantly.

It's always good to read some good feedback, thanks.


On Wed, Feb 25, 2015 at 4:39 PM, achary <notifications@github.com> wrote:

> oh, I see. thanks.
> no problem at all.
> for some reasons I wasn't sure and the two above was the way I found
> working...
>
> Anyway. FakeIt seems doing very good job in my opinion. The fact that there
> is no so much code generation for pure mocking (that's really a winning
> point to me in comparison to gmock for example) is just great!
>
> And the syntax of instantiating mock from pure abstract class right in the
> test case - just sweet.
>
> I'm really impressed and I personally think it's one of greatest mocking
> lib for C++ out there.
>
> I've noticed that stubbing generates pretty lot of code and large binaries
> (at least when you oscillate in ranges of hundreds to 1000 methods to
> stub).
>
> Could that potentially be elimintated? E.g. by assuming some no-action
> default stubbing for "void foo(...)" like methods and e.g. returning
> default values in case of non-void return value types?.
>
> cheers,
> Adam
>
>
> 2015-02-25 12:11 GMT+00:00 eranpeer <notifications@github.com>:
>
> > Hi,
> > I've just noticed that you added an "include" section to the quickstart.
> > Thanks for your help.
> > I've changed the section a little. The only file you have to include is:
> > fakeit.hpp
> > On Feb 24, 2015 1:33 AM, "achary" <notifications@github.com> wrote:
> >
> > > Superb, thanks.
> > > A 1000 seems is truely good enought for me.
> > > (although I work in with range of 400 rather frequently).
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/eranpeer/FakeIt/issues/13#issuecomment-75661705>.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/eranpeer/FakeIt/issues/13#issuecomment-75949802>.
> >
>
>
>
> --
> Adam Charytoniuk
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eranpeer/FakeIt/issues/13#issuecomment-75970327>.
>



-- 
Eran
972-52-8387550

**Comment by eranpeer** [comment]
Using -O3 compilation flag with MinGW64 reduces the compile time of fakeit tests from 8 minutes to 2 minutes on my laptop.
Do you use -O3 flag when building your test binary?

**Comment by achary** [comment]
I was using -O0 switch all the time and debug build type. That is
unfortunetely requirement I need to stick to i n my project for the buils
with tests.


2015-02-28 18:52 GMT+00:00 eranpeer <notifications@github.com>:

> Using -O3 compilation flag with MinGW64 reduces the compile time of fakeit
> tests from 8 minutes to 2 minutes on my laptop.
> Do you use -O3 flag when building your test binary?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eranpeer/FakeIt/issues/13#issuecomment-76539793>.
>



-- 
Adam Charytoniuk

**Comment by eranpeer** [comment]
What abot -flto flag (link time optimization) this cuts the size of the
binary by 90% !! when I build the fakeit tests project on MinGW64.
You can compile the production code without that flag and use it only for
compiling your tests.

**Comment by achary** [comment]
I will try this in day or two.
unfortunatelly what GCC doc is saying is:
Link-time optimization does not work well with generation of debugging
information.

and I need debug symbols in my tests..

cheers,
a

2015-03-02 6:15 GMT+00:00 eranpeer <notifications@github.com>:

> What abot -flto flag (link time optimization) this cuts the size of the
> binary by 90% !! when I build the fakeit tests project on MinGW64.
> You can compile the production code without that flag and use it only for
> compiling your tests.
>
> On Mar 1, 2015 10:58 PM, "achary" <notifications@github.com> wrote:
>
> > I was using -O0 switch all the time and debug build type. That is
> > unfortunetely requirement I need to stick to i n my project for the buils
> > with tests.
> >
> >
> > 2015-02-28 18:52 GMT+00:00 eranpeer <notifications@github.com>:
> >
> > > Using -O3 compilation flag with MinGW64 reduces the compile time of
> > fakeit
> > > tests from 8 minutes to 2 minutes on my laptop.
> > > Do you use -O3 flag when building your test binary?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/eranpeer/FakeIt/issues/13#issuecomment-76539793>.
> > >
> >
> >
> >
> > --
> > Adam Charytoniuk
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/eranpeer/FakeIt/issues/13#issuecomment-76630236>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eranpeer/FakeIt/issues/13#issuecomment-76663441>.
>



-- 
Adam Charytoniuk
