### ISSUE TITLE
Support for const function overloads.

### ISSUE THREAD

**Issue by c0yote** [eranpeer/FakeIt#14]
I may just be doing it wrong, but I can't find a way to return from a const overload.  I checked the project's unit test code and didn't find any examples.

Support for the following situation would be highly appreciated.

    virtual Foo& GetBar();
    virtual const Foo& GetBar() const;

Love the framework, thanks for all of your effort!

**Comment by eranpeer** [comment]
Your doing just fine. It seems like Fakeit doesn't support const overload.
I will try to solve this issue this weekend.
Thanks,
Eran.

**Comment by eranpeer** [comment]
Ok, I added a ConstOverloadedMethod macro that is used just like the OverloadedMethod macro.
For example:
```C++
struct SomeInterface {
  virtual int func() = 0;
  virtual int func() const = 0;
}

Mock<SomeInterface> mock;
When(OverloadedMethod(mock, func, int())).Return(1);
When(ConstOverloadedMethod(mock, func, int())).Return(2);

SomeInterface &obj = mock.get();
const SomeInterface& constObj = mock.get();

ASSERT_EQUAL(1, obj.func());
ASSERT_EQUAL(2, constObj.func());
```
Thank you for submitting this issue. Fakeit is better now!!

**Comment by eranpeer** [comment]
BTW,
I added some more samples to the overloadded_methods_tests.cpp file.
I hope this helps.

**Comment by c0yote** [comment]
Thanks!  Works like a champ!
