### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by helmesjo** [eranpeer/FakeIt#155]
A few things have happened since the latest release (May 21, 2017), including a lot of fixes for catch2 compatibility.

Could a new version be release? I'm using conan for dependency management, and it's policy is sort of to only target exact versions. :)

Thanks!

**Comment by eranpeer** [comment]
Done! There is a new pre-release: 2.0.5.
In few days it will be an official one.

**Comment by helmesjo** [comment]
@eranpeer Thanks! Please ping me here when its out of pre-release state.
