### ISSUE TITLE
Boost unit error output under MSVC 2013 is not formatted properly to allow double click

### ISSUE THREAD

**Issue by sleep-deprived** [eranpeer/FakeIt#16]
And another one:
I'm using Boost test, MSVC 2013.
When there's a verify error, the info is printed (test case name, file and line) but it appears on the same line as BoostTestFakeit.hpp(22), and is not exactly in the correct format (line number in parentheses, and I think absolute path is also required), so I can't double click in the output panel to take me to the correct location in the unit test source file.

It might sound nit-picky, but searching for the correct source file in a large project instead of double clicking is time wasting...

Thanks.

**Comment by eranpeer** [comment]
No you're not nit-picky. Thank you for your feedback.
Double clicking should work now & the error message should point to the correct location.
You can clone and and try it.
I will close this issue. Please reopen if it does not work correctly for you.

**Comment by sleep-deprived** [comment]
Works, thanks!
