### ISSUE TITLE
support for the doctest testing framework

### ISSUE THREAD

**Issue by onqtam** [eranpeer/FakeIt#164]
regarding this Catch-like testing framework: https://github.com/onqtam/doctest

trompeloeil already has support for it: https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#adapt_doctest

**Comment by Di3mex** [comment]
What is the status on this? I am exploring different Mocking/Stubbing/Faking libraries and FakeIt has a nice syntax. The standalone header errors out with an unknown error when run from doctest.

**Comment by FranckRJ** [comment]
It's the first thing I'll work on for the 2.3. The 2.2 will be released this month.

**Comment by FranckRJ** [comment]
Added in #275.
