### ISSUE TITLE
Convert Verify() result to bool

### ISSUE THREAD

**Issue by sleep-deprived** [eranpeer/FakeIt#17]
And last one (for now) -

Is it possible to have Verify() (or Verify().Once() etc.) to be convertible to bool?
I have cases where I want to know programatically in the test whether the condition is true.

Thanks.

**Comment by eranpeer** [comment]
Thank's for all your feedback, it is very appreciated.
Well, I cant change Verify() to return bool since then we will not be able to write: Verify(...).Once()
I will consider returning a bool form the the Once() method (and all the other: twice, exactly atleast... ) as it will not break any currently supported functionality.
Thanks,

**Comment by sleep-deprived** [comment]
Thanks for your support :)

I didn't mean that Verify() should return bool, just that it can be *convertible* to bool.

**Comment by eranpeer** [comment]
Ok, It works.
Verify is convertible to bool now.
Here is a usage example:
```c++
struct AnInterface {
    virtual int func(int) = 0;
};
Mock<AnInterface> mock;
When(Method(mock, func)).AlwaysReturn(0);

AnInterface &obj = mock.get();
obj.func(1);

ASSERT_TRUE(Verify(Method(mock, func).Using(1)));
ASSERT_FALSE(Verify(Method(mock, func).Using(2)));
ASSERT_TRUE(Verify(Method(mock, func).Using(1)).AtLeast(1));
ASSERT_TRUE(Verify(Method(mock, func).Using(1)).AtLeastOnce());
ASSERT_TRUE(Verify(Method(mock, func).Using(1)).Exactly(1));
ASSERT_TRUE(Verify(Method(mock, func).Using(1)).Once());
ASSERT_FALSE(Verify(Method(mock, func).Using(1)).Twice());
ASSERT_FALSE(Verify(Method(mock, func).Using(1)).Never());
```
Thank you for submitting this enhancement request.
I hope you'll find it usable.

**Comment by sleep-deprived** [comment]
Thanks for your work.

Seems to work for Verify, but VerifyNoOtherInvocations does not have this conversion.

I've added the following code to VerifyNoOtherInvocationsVerificationProgress.hpp (under public):

    operator bool() {
        try{
            _ptr->VerifyExpectation();
            return true;
        }
        catch (...){
            return false;
        }
    }

Not sure if it's enough, but it compiles now :)

תודה וחג שמח

**Comment by eranpeer** [comment]
Thanks,
I made the change to VerifyNoOtherInvocationsVerificationProgress.hpp. It is now convertible to bool.
I also fixed a memory leak and other minor issues. I suggest you pull the latest version.
בכיף, חג שמח
