### ISSUE TITLE
Is it possible to fake a function that invokes a callback that is one of its parameters?

### ISSUE THREAD

**Issue by TrueWodzu** [eranpeer/FakeIt#175]
Hi,

I wanted to ask, because I haven't seen such example. If I have a function like this:

`
bool MyFunction(MyCallback callback)
{
  callback(param1, param2);
  return true;
}
`

Is it possible to fake it in a way that it will call the callback which is inside of it?

Thanks.

**Comment by alibabashack** [comment]
Yes, see https://github.com/eranpeer/FakeIt/wiki/Quickstart
You can use the lambda expression forms:
```
When(Method(mock,foo)).Do([](int a)->int{ ... });
When(Method(mock,foo)).AlwaysDo([](int a)->int{ ... });
```

**Comment by uglide** [comment]
It doesn't work with code like that:
```
When(Method(mock,foo)).Do([](std::function<void()> a)->bool{ a(); return true; });
```

Returns the following error during tests execution:
```
Unexpected method invocation: unknown()
  An unmocked method was invoked. All used virtual methods must be stubbed!
```
