### ISSUE TITLE
Add support for BiiCode

### ISSUE THREAD

**Issue by skizzay** [eranpeer/FakeIt#19]
It's not really an issue, but more of a wish.  As a developer writing unit tests with mock objects, I want to be able to easily get prepackaged code from a dependency management, such as BiiCode, so that I can incorporate this mocking functionality without having to know any Cmake magic or handle downloading/cloning repositories.

**Comment by eranpeer** [comment]
FakeIt is now on biicode.
Please add the following lines to the biicode.conf file of your project:
* Add the following line to the [Requirements] section:
```
eranpeer/FakeIt: 0 
```
* Add ONE of the following lines to the [includes] section:
```
fakeit.hpp: eranpeer/FakeIt/config/gtest       # To use fakeit with gtest
fakeit.hpp: eranpeer/FakeIt/config/boost       # To use fakeit with boost test
fakeit.hpp: eranpeer/FakeIt/config/mstest      # To use fakeit with mstest
fakeit.hpp: eranpeer/FakeIt/config/tpunit      # To use fakeit with tpunit
fakeit.hpp: eranpeer/FakeIt/config/standalone  # To use fakeit with standalone configuration.
```
I will close this issue. Please reopen it if you encounter any problem.
Thank you for submitting this issue. FakeIt is better now!
