### ISSUE TITLE
Segfault when a spied method calls another method

### ISSUE THREAD

**Issue by jvff** [eranpeer/FakeIt#20]
I would like to spy a given class to make sure one method invocation results in the invocation of some other methods. While attempting to do that, the code always segfaults. I suspect the reason is that the `this` pointer seems to be different, but I don't know why. I managed to reduce the test code into the following dummy test case:

    #include <gtest/gtest.h>
    #include <fakeit.hpp>
    
    using namespace fakeit;
    
    class Dummy {
    public:
        virtual void method() {
            printf("Method called\n");
        }
    
        virtual void callMethod() {
            printf("this: %p\n", (void*)this);
            this->method();
        }
    };
    
    TEST(DummyTest, simpleTest) {
        Dummy instance;
        auto spy = Mock<Dummy>(instance);
    
        Spy(Method(spy, method));
        Spy(Method(spy, callMethod));
    
        instance.callMethod();
        spy.get().callMethod();
    }

Tested with HEAD @ 15b8e3519a42b2a89cf9f232647f95de83e720cb

**Comment by eranpeer** [comment]
Please specify the compiler you use and all compilation flags.

**Comment by jvff** [comment]
Compiled with the following command line:

    $ g++ -std=c++11 test.cpp -I ~/lib/fakeit/include -I ~/lib/fakeit/config/gtest -lgtest -lgtest_main -pthread

Compiler version:

    $ g++ --version
    g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

System info:

    $ uname -a
    Linux jvff-workstation 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eranpeer** [comment]
OK, I fixed it. It was a bug!
I also added your test to the file tests/spying_tests.cpp.
Please pull the latest commit, it should work now.
Thank you for submitting this issue, FakeIt is better now!

**Comment by jvff** [comment]
It's working perfectly now! Thank you very much! Also, congratulations on the library, it is awesome =)
