### ISSUE TITLE
Any way to speed up compile time?

### ISSUE THREAD

**Issue by kammce** [eranpeer/FakeIt#213]
I'm trying to speed up the process of building unit tests and I currently bottle necked by FakeIt. FakeIt seems to take up the majority of the build time for compilation. Are there any defines that I can use to reduce the feature set and increase compilation speed?

**Comment by Ambrou** [comment]
Hi,
Did you try to use precompiled header ?
FakeIt is just header code, so you can reduce the compile time by this way

Ambrou

**Comment by kammce** [comment]
Actually I was able to greatly reduce my compile time by unity/jumbo building my unit tests. Got my test build times from 10 minutes down to 1m40s.
