### ISSUE TITLE
Access underlying instance in `Do` lambda

### ISSUE THREAD

**Issue by dmeehan1968** [eranpeer/FakeIt#217]
I had a requirement to add a stopwatch over a on/off method pair of an object, and decided to do that with a `When(Method(class, method)).AlwaysDo(...)` call.

However, I still needed to call the underlying instance implementation, but this doesn't appear to be accessible from within the Mock<class> instance.  e.g. 

```
class foo {
public: 
  void bar() { }
};
Mock<foo> mock;
foo & instance = mock.get();  // <--this is a the mocked instance, not the underlying instance
When(Method(foo, bar)).AlwaysDo([&instance](){
  // do stopwatch code
  instance.get().bar(); // <-- this is recursive, calling the lambda until stack exhausted
});
```

The only way I could see to do it was to create my own underlying instance, and then pass that to the mock constructor:

```
foo _foo;
Mock<foo> mock(_foo);
When(Method(foo, bar)).AlwaysDo([&_foo](){
  // do stopwatch code
  _foo.bar(); // <-- this is NOT recursive
});
```

Another approach is to write a wrapper for the foo class, but that was more verbose in terms of code, and might be more prone to error for more complex classes.

It seems that spy's could really do with a `getInstance()` method to provide a reference to the underlying instance. I'm not c++ expert, there might be an alternative way of doing this.

**Comment by dmeehan1968** [comment]
Way to far in the past for me to remember the context of this, and as you point out, it would appear to be more sugar than necessity.

**Comment by FranckRJ** [comment]
Ok, I'll close this issue, if you ever need it again you can always reopen it (i guess) or at least create a new one.
