### ISSUE TITLE
FakeIt should not throw things that aren't derived from std::exception.

### ISSUE THREAD

**Issue by VirtualTim** [eranpeer/FakeIt#223]
So I was investigating an occasional unit test failure resulting in the only info being reported being "uncaught exception of unknown type".
So I thought I'd take a look to see what exceptions FakeIt throws, so I could determine why cppunit wasn't catching them. As it turns out, lots of different things. All things that are thrown should inherit from std::exception, or people using fakeit will never catch them.

At a quick look, here's the ones I found:
https://github.com/eranpeer/FakeIt/blob/814f28cd509ef2a8cdf7fe370bd9ec6d3b181dc7/include/fakeit/ThrowFalseEventHandler.hpp#L12 (edit: the above is actually OK, as it's only thrown from one spot that explicitly catches bools)
https://github.com/eranpeer/FakeIt/blob/814f28cd509ef2a8cdf7fe370bd9ec6d3b181dc7/config/cute/CuteFakeit.hpp#L17
https://github.com/eranpeer/FakeIt/blob/814f28cd509ef2a8cdf7fe370bd9ec6d3b181dc7/include/fakeit/FakeitExceptions.hpp#L25
https://github.com/eranpeer/FakeIt/blob/814f28cd509ef2a8cdf7fe370bd9ec6d3b181dc7/include/mockutils/DefaultValue.hpp#L41-L51
where https://github.com/eranpeer/FakeIt/blob/814f28cd509ef2a8cdf7fe370bd9ec6d3b181dc7/include/mockutils/DefaultValue.hpp#L16

**Comment by FranckRJ** [comment]
It looks like it's on purpose : https://github.com/eranpeer/FakeIt/blob/814f28cd509ef2a8cdf7fe370bd9ec6d3b181dc7/include/fakeit/FakeitExceptions.hpp#L39-L40

**Comment by VirtualTim** [comment]
Hm, I don't really understand that explanation.
The issue I was getting is that I have some tests (using FakeIt + cppunit) that were occasionally failing with `exception: uncaught exception of unknown type`. This obviously gives me next to nothing to go on.

After changing FakeitException to inherit from std::exception the actual error was revealed; `uncaught exception of type std::exception (or derived). - Unexpected method invocation: unknown() An unmocked method was invoked. All used virtual methods must be stubbed!`.

So I'm not really sure why someone would want the existing behaviour. Best case you crash, worst case you get failures with no information in them.

**Comment by FranckRJ** [comment]
No, I've read the code a bit and it's exactly what should happen.

So, in short when there is an error of this kind (unexpected method call,
etc) an handler is called to handle the event. Handler should be written in
a way the test framework can catch the error but not the tested code. The
way it's done in the standalone version is by throwing exception that
aren't derived from std::exception, so you can be sure that the tested code
can't catch it and that you will be able to catch it in the test itself.

So, you either need to write a new handler for cppunit or catch these
exceptions yourself, but deriving these exception from std::exception would
make the error very hard to catch on the test level (and probably brake a
lot of existing code).

Le lun. 22 mars 2021 à 08:50, Tim Lander ***@***.***> a
écrit :

**Comment by VirtualTim** [comment]
OK. I don't really like that design, as it sounds like I either need to make modifications to cppunit which tightly couple it to FakeIt, or wrap all the unit tests which use FakeIt with FakeIt-spesific exception handlers.

But it that's intentional then fair enough. But I suspect this will be an issue other people will run into, so should probably be documented somewhere. I couldn't even find what type of stuff FakeIt throw without searching through the code.

**Comment by FranckRJ** [comment]
You don't need to make modifications to cppunit, you need to write a
cppunit handler for fakeit (like the one fore catch or all other supported
test frameworks, look inside the config folder).

How else could it be done ?

**Comment by VirtualTim** [comment]
Cppunit has an exception handler that catches anything uncaught.
So regardless of what FakeIt actually throws, it ends up getting caught. The only difference is if the caught thing is derived from std::exception we get the contents of "what()", otherwise we get a generic message. ([code here](https://github.com/Ultimaker/CppUnit/blob/a79b0e2674783ff4045e80fe0b193d6c4b860991/src/cppunit/DefaultProtector.cpp#L9-L39), not "official", but the simplest source I could find).

So I guess from my point of view changing FakeitException to be derived from std::exception fixes the issue. But like you said this could break existing code written for different test frameworks.

For now I'm just using a fork of FakeIt with the std::exception change, and I guess the only way to "fix" this from the FakeIt side is to write a cppunit specific handler.
