### ISSUE TITLE
Spewing of "unknown pragma" warnings on MSVC

### ISSUE THREAD

**Issue by helmesjo** [eranpeer/FakeIt#230]
It appears one of the more recent changes cause this to be spewed all over the MSVC build (probably from [this](https://github.com/eranpeer/FakeIt/pull/214) PR). See the latest [build](https://ci.appveyor.com/project/eranpeer/fakeit/builds/38327359).

```c++
c:\projects\fakeit\include\mockutils\union_cast.hpp(12): warning C5030: attribute 'gnu::optimize' is not recognized [C:\projects\fakeit\tests\all_tests.vcxproj]
c:\projects\fakeit\include\mockutils\vtutils.hpp(25): warning C4068: unknown pragma [C:\projects\fakeit\tests\all_tests.vcxproj]
c:\projects\fakeit\include\mockutils\vtutils.hpp(26): warning C4068: unknown pragma [C:\projects\fakeit\tests\all_tests.vcxproj]
c:\projects\fakeit\include\mockutils\vtutils.hpp(33): warning C4068: unknown pragma [C:\projects\fakeit\tests\all_tests.vcxproj]
```

**Comment by FranckRJ** [comment]
Yes, I will maybe look at it but I think it's good practice to lower /
remove external headers warnings anyway :
https://devblogs.microsoft.com/cppblog/broken-warnings-theory/

It's what GCC / clang do with -Isystem, so you will have a consistent
behavior across compilers.

**Comment by helmesjo** [comment]
Yeah that's what I usually opt for (and did in this case), but thanks for the interesting read!
