### ISSUE TITLE
String literals not being matched correctly v2.0.7.

### ISSUE THREAD

**Issue by zfields** [eranpeer/FakeIt#232]
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.out is a Catch v2.13.4 host application.
Run with -? for options

-------------------------------------------------------------------------------
PseudoSensor::temp() generates a `card.temp` request
-------------------------------------------------------------------------------
pseudo-sensor.test.cpp:11
...............................................................................

pseudo-sensor.test.cpp:27: FAILED:
  Verify( mock_notecard.newRequest("card.temp") )
with message:
  pseudo-sensor.test.cpp:27: Verification error
  Expected pattern: mock_notecard.newRequest("card.temp")
  Expected matches: exactly 1
  Actual matches  : 0
  Actual sequence : total of 1 actual invocations:
    mock_notecard.newRequest("card.temp")

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed
```

I ran the verification with increasing requirements to narrow it down, for example...

```c++
fakeit::Verify(Method(mock_notecard,newRequest));                           // passes
fakeit::Verify(Method(mock_notecard,newRequest)).Once();                    // passes
fakeit::Verify(Method(mock_notecard,newRequest).Using("card.temp")).Once(); // fails
```
The call in the implementation under test looks like this:

```c++
_notecard.newRequest("card.temp");
```

The signature of the mocked method is:

```c++
virtual J *  newRequest(const char *) = 0;
```

**Comment by zfields** [comment]
I ran some quick tests, and it appears to be comparing pointers instead of comparing the strings at the pointers.

If I declare a global variable for the string, then it works. Otherwise, whether literals or variables, it fails.

**Comment by FranckRJ** [comment]
It's the intended behavior. If you don't want to use `==` for comparison you should use matchers : https://github.com/eranpeer/FakeIt/wiki/Quickstart#invocation-matching.

**Comment by zfields** [comment]
@FranckRJ Thank you for responding so quickly. I read the documentation you referenced, but I don't see how **Matchers** would be the correct tool for an EXACT comparison of strings.

Again, the code looks like this...

```c++
_notecard.newRequest("card.temp");
```

The signature looks like this...

```c++
virtual J *  newRequest(const char *) = 0;
```

The check looks like this...

```c++
fakeit::Verify(Method(mock_notecard,newRequest).Using("card.temp")).Once(); // fails
```

Can you can provide an example of how a **Matcher** would be used in this arrangement? If this is the preferring mechanism, I think an example will help several others in my predicament.

Also, I'm failing to understand in what circumstance `==` would be viable for testing strings of type `const char *`. Could you also explain the reasoning behind this decision?

**Comment by FranckRJ** [comment]
There is an example in the wiki :

```cpp
auto argument_a_is_even = [](int a){return a%2==0;};
When(Method(mock,foo).Matching(argument_a_is_even)).Return(1);
```

For `Verify` it's the same, in the wiki it's the section just below the one I linked :

**Comment by FranckRJ** [comment]
There is an example in the wiki :

```cpp
auto argument_a_is_even = [](int a){return a%2==0;};
When(Method(mock,foo).Matching(argument_a_is_even)).Return(1);
```

For `Verify` it's the same, in the wiki it's the section just below the one I linked :

```cpp
Verify(Method(mock,bar).Matching([](int a, int b){return a > b;})).Exactly(Once);
```

In your specific use case it should look like :

```cpp
Verify(Method(mock,bar).Matching([](const char* str){return strcmp(str, "card.temp") == 0;})).Exactly(Once);
```

> Also, I'm failing to understand in what circumstance == would be viable for testing strings of type const char *. Could you also explain the reasoning behind this decision?

Probably never, that's why you don't use `const char *` for representing strings in C++.

**Comment by zfields** [comment]
Thank you for the example, I will update my test immediately! Also, It would be great if you could clarify the documentation to reflect that it works for verification as well.

While we're on the subject...

> Probably never, that's why you don't use `const char *` for representing strings in C++.

I'm sure you're being cheeky here, but this statement effectively equates to don't use FakeIt if you didn't write the code you're trying to mock/test. Any time a string literal is used, it will be converted, by the compiler, to `const char *`, so it's not a type the developer gets to choose.

Also, string literals are not so uncommon that they should not be natively supported by the framework. It is awesome the framework is so flexible it can accommodate, but since there is _"Probably never"_ a reason to test `const char *` strings with `==`, then it would be nice for FakeIt to overload the `.Using()` method to convert the type `const char *` to `std::string` before testing with `==`.

**Comment by FranckRJ** [comment]
> Any time a "string literal" is used, it will be converted, by the compiler, to const char *, so it's not a type the developer gets to choose.

You're choosing the type of the arguments of your functions, nothing force you to use `const char *`.

> it would be nice for FakeIt to overload the .Using() method to convert the type const char * to std::string before testing with ==.

No, because a `const char *` isn't necessary a string.

**Comment by zfields** [comment]
> You're choosing the type of the arguments of your functions, nothing force you to use const char *.

Definitely not. I'm adhering to an interface, that I did NOT create. Which is precisely why interfaces exist - not mocking.

> No, because a `const char *` isn't necessarily a string.

Fair point.

**Comment by FranckRJ** [comment]
>>You're choosing the type of the arguments of your functions, nothing force you to use const char *.

>Definitely not. I'm adhering to an interface, that I did NOT create. Which is precisely why interfaces exist - not mocking.

You're right, then you should use matchers.

**Comment by FranckRJ** [comment]
I've created an issue for it : #234.

If you think this solution will be good for you, please close this issue.

**Comment by zfields** [comment]
Thanks! I really appreciate it, the conversation, and the workaround.
