### ISSUE TITLE
Missing defines in single header for catch2

### ISSUE THREAD

**Issue by poeschlr** [eranpeer/FakeIt#252]
Hi,

the defines `CATCH_INTERNAL_START_WARNINGS_SUPPRESSION` and `CATCH_INTERNAL_STOP_WARNINGS_SUPPRESSION` are not defined anywhere in https://github.com/eranpeer/FakeIt/blob/master/single_header/catch/fakeit.hpp#L1223. (I reverted it back to the old version for our local runs but i assume the proper fix would be to define these two macros)

Edit: the version of the header i looked at had version info: `Generated: 2021-05-12 13:47:04.979584`

**Comment by FranckRJ** [comment]
They are in catch2, not in fakeit.

**Comment by FranckRJ** [comment]
FakeIt 2.1 improve support for older versions of catch2 (where these headers weren't available). So I guess your issue should be fixed.

**Comment by FranckRJ** [comment]
I'll close this issue as I guess it's fixed. If it's not the case you can reopen it.
