### ISSUE TITLE
Using global objects to assign output of get() method

### ISSUE THREAD

**Issue by fgr-17** [eranpeer/FakeIt#253]
Hello!

I'm using FakeIt lib with Catch2.
I'm having some issues when I try to verify global mocked objects methods execution. 

First, a working example:

```
class SomeInterface {
  void fun(void) {}
}; 

TEST_CASE("mock test", "[test]") {
  
  Mock<SomeInterface> mock;
  Fake(Method(mock, fun));
  SomeInterface&i=mock.get();
  
  i.toggle();

  Verify((Method(mock, toggle)).AtLeastOnce();
}

```

But if the object assigned by mock.get() is global, the compilation builds OK, but the verify test fail.

How can I overcome this?

**Comment by FranckRJ** [comment]
Can you provide exactly the code that fails ? Looks like you copying the mock instead of using a reference to it but I'm not sure.

**Comment by FranckRJ** [comment]
I'll close it as there was no answer for one year.
