### ISSUE TITLE
Overloaded function in derived class hides base class function

### ISSUE THREAD

**Issue by otrempe** [eranpeer/FakeIt#284]
```
class IBase
{
public:
    virtual ~IBase() = default;

    virtual void MyOverloadedFunction( int )            = 0;
    virtual void MyConstOverloadedFunction( int ) const = 0;
};

class IDerived : public IBase
{
public:
    virtual void MyOverloadedFunction( double )            = 0;
    virtual void MyConstOverloadedFunction( double ) const = 0;
};

{
    fakeit::Mock< IDerived > mock;
    fakeit::When( OverloadedMethod( mock, MyOverloadedFunction, void( double ) ) );
    fakeit::When( ConstOverloadedMethod( mock, MyConstOverloadedFunction, void( double ) ) );

    fakeit::When( OverloadedMethod( mock, MyOverloadedFunction, void( int ) ) );
    fakeit::When( ConstOverloadedMethod( mock, MyConstOverloadedFunction, void( int ) ) );
}
```
> error C2664: 'void (__cdecl IDerived::* fakeit::Prototype<void (int)>::MemberType<IDerived>::get(void (__cdecl IDerived::* )(int)))(int)': cannot convert argument 1 from 'void (__cdecl IDerived::* )(double)' to 'void (__cdecl IDerived::* )(int)'
> note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
> error C2672: 'fakeit::Mock<IDerived>::stub': no matching overloaded function found
> error C2672: 'operator __surrogate_func': no matching overloaded function found
> 
> error C2664: 'void (__cdecl IDerived::* fakeit::Prototype<void (int)>::MemberType<IDerived>::getconst(void (__cdecl IDerived::* )(int) const))(int) const': cannot convert argument 1 from 'void (__cdecl IDerived::* )(double) const' to 'void (__cdecl IDerived::* )(int) const'
> note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
> error C2672: 'fakeit::Mock<IDerived>::stub': no matching overloaded function found
> error C2672: 'operator __surrogate_func': no matching overloaded function found

**Comment by otrempe** [comment]
The workaround is to redeclare the base class function in the derived class

**Comment by FranckRJ** [comment]
That's how C++ works, it isn't an issue with the library.

You don't need to redeclare the function, you can also "import" it.

```
class IDerived : public IBase
{
public:
    using IBase::MyOverloadedFunction;
    using IBase::MyConstOverloadedFunction;
    virtual void MyOverloadedFunction( double )            = 0;
    virtual void MyConstOverloadedFunction( double ) const = 0;
};
```

**Comment by otrempe** [comment]
You're right. I got fooled by Visual Studio 2017 compiling this as valid code.

**Comment by otrempe** [comment]
Non virtual function should hide base class function, but virtual function should be fine.
This scheme compiles fine on all compiler versions I tried without importing base class functions.

**Comment by FranckRJ** [comment]
The function being virtual or not change nothing, it's the same rules.

As you can see : https://godbolt.org/z/6f4h4nPMW

**Comment by otrempe** [comment]
You're right, I was fooled by my test using the wrong type for calling the overloaded function.
