### ISSUE TITLE
compiled error with c++17 in VS2019

### ISSUE THREAD

**Issue by zhlongfj** [eranpeer/FakeIt#285]
error info:
”fakeit::NoVirtualDtor::NoVirutualDtor“：static member method does not have "this" point

**Comment by malcolmdavey** [comment]
Can you give an example of the test you are trying to write?

BTW, I'm using C++17 with VS 2019 (v142 toolset), so can easily compare what I get.

**Comment by zhlongfj** [comment]
I found the problem this morning, I changed "TARGET" to "TARGET1" in "template<typename TARGET, typename SOURCE>"(Line: 5256).
It's OK now, aybe naming conflicts, but I didn't find "TARGET" in project.

**Comment by zhlongfj** [comment]
> Can you give an example of the test you are trying to write?
> 
> BTW, I'm using C++17 with VS 2019 (v142 toolset), so can easily compare what I get.

I found the problem this morning, I changed "TARGET" to "TARGET1" in "template<typename TARGET, typename SOURCE>"(Line: 5256).
It's OK now, aybe naming conflicts, but I didn't find "TARGET" in project.

**Comment by FranckRJ** [comment]
I'll keep it open just to remember to rename these templates parameters. They shouldn't be in uppercase anyway because it lay cause issues with macro (probably what happened for you).

**Comment by FranckRJ** [comment]
Should be fixed by #300, in FakeIt 2.3.1.
