### ISSUE TITLE
complied error when mock with unique_ptr

### ISSUE THREAD

**Issue by zhlongfj** [eranpeer/FakeIt#287]
My Code:
Mock<ITimeLineSchedulerCore> schedulerCoreMock;
auto schedulerCore = unique_ptr<ITimeLineSchedulerCore>(&schedulerCoreMock.get(), [](auto) {});

Complied Error:
<function-style-cast> : cannot be converted from "initializer list" to "std::unique_ptr<kompasstimeline::ITimeLineSchedulerCore,std::default_delete<kompasstimeline::ITimeLineSchedulerCore>>"

**Comment by FranckRJ** [comment]
This is unrelated to this library, it's just a miss use of the STL. Try with another class like std::string instead of fakeit::Mock and you'll have the same error. Check the documentation to know how unique_ptr works : https://en.cppreference.com/w/cpp/memory/unique_ptr

**Comment by malcolmdavey** [comment]
@zhlongfj Looks like this one has been resolved

**Comment by FranckRJ** [comment]
I'll close this issue because I guess it was resolved.
