### ISSUE TITLE
Support for x64 on VS2015 and VS2013

### ISSUE THREAD

**Issue by mflai** [eranpeer/FakeIt#30]
Unit tests for FakeIt is failing on Visual Studio. By looking at the code I believe it came from:
1. pointers being converted to int leading to seg-fault. (int is still 32bit on x64 Visual Studio)
2. There might be changes in the "header" of the VTable.

Is FakeIt planning to support x64 on Windows? If so let's get this fixed I don't minding lending a hand=)

**Comment by eranpeer** [comment]
Thanks, it looks like a bug. Please, if you have time, you are more than
welcome to to lend a hand and submit a pull request.

**Comment by DavidMFLai** [comment]
Sure I will give that a shot.

**Comment by DavidMFLai** [comment]
I am developing on VS2015.

Turns out that it can get very deep. The issue is that the type information (RTTICompleteObjectLocator) is no longer stored in *vftable[-1] for 64 bit compilations. We may require a lot of changes across the board for this.

**Comment by eranpeer** [comment]
Well, It woks fine for me (besides some compiler cast warnings).
All tests pass on x64.
I'm using the VS2015 community edition.

**Comment by DavidMFLai** [comment]
Mine's still failing:

OS: Windows 10 Home
Compiler/IDE: VS2015 Community Edition

The following are my command-line options:
/GS /W3 /Zc:wchar_t /I"..\include" /I"..\config\standalone" /ZI /Gm /Od /sdl /Fd"x64\Debug\vc140.pdb" /Zc:inline /fp:precise /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MDd /Fa"x64\Debug\" /EHsc /nologo /Fo"x64\Debug\" /Fp"x64\Debug\all_tests.pch"

**Comment by eranpeer** [comment]
Oops, I was wrong. I ran the wrong exe. Mine is failing too.

**Comment by eranpeer** [comment]
It looks like the RTTICompleteObjectLocator is still in  *vftable[-1]  though its structure is different.
The last 2 pointers: pTypeDescriptor & pClassDescriptor are just DWORD numbers now.
I cant find the way to construct a fake RTTICompleteObjectLocator for a mock.
Any idea?

**Comment by DavidMFLai** [comment]
I tried to view the structure of a simple class A in x64 and got the following:
class A {
     int a;
}

 1>  class Aclass	size(16):
1>  	+---
1>   0	| {vfptr}
1>   8	| a
1>    	| <alignment member> (size=4)
1>  	+---
1>
1>  Aclass::$vftable@:
1>  	| &Aclass_meta
1>  	|  0
1>   0	| &Aclass::setA
1>
1>  Aclass::setA this adjustor: 0
1>
1>
1>  class ?$RTTICompleteObjectLocator@VAclass@MscTypeInfoTests@@$$V	size(32):
1>  	+---
1>   0	| signature
1>   4	| offset
1>   8	| cdOffset
1>    	| <alignment member> (size=4)
1>  16	| pTypeDescriptor
1>  24	| pClassDescriptor
1>  	+---

From the looks of it, pTypeDescriptor is still a pointer (8 bytes) but I do not know what it points to. Nevertheless, pTypeDescriptor != &typeid(AClass), but it is in x86.


I wish I could find more documentation on this but I cannot find any.

**Comment by eranpeer** [comment]
I found a clue:
" the x64 RTTI uses offsets from the base instead of pointers"
I found it here: 
https://www.unknowncheats.me/forum/general-programming-and-reversing/145833-reclass-2015-a-3.html

The only question is what is "base". once I know that, I can solve this issue.

**Comment by eranpeer** [comment]
the pTypeDescriptor & pClassDescriptor are just DWORD with "offsets form base"???

**Comment by DavidMFLai** [comment]
Thanks for the very decent information. You might want to pull my branch "feature/VisualStudioX64". It contains information on using the BaseModule's address together with the offsets to find our std::type_info. See msc_type_info_tests.cpp

The rest will be up to you!

Btw, you might want to upgrade the CI to VS2015!!

**Comment by 0rigin85** [comment]
Hi, I just want to throw in my vote for supporting x64. Is this something you've decided to active pursue? We're looking at using your library but the lack of x64 is a bit crippling for our needs, though the library features are awesome.

**Comment by eranpeer** [comment]
I'm making big efforts trying to support x64 though currently I have no
success. It looks like Microsoft made good work in blocking me. Hope for
more success in the future.

**Comment by HansKester** [comment]
Is there any progress on this issue? We would like to use 64 bit as well...

**Comment by tnovotny** [comment]
I am currently using [hippomocks](https://github.com/dascandy/hippomocks). That supports x64, so maybe you can check his code or ask the author.

**Comment by ericlemes** [comment]
I'm closing this issue since is not active and I've got this working on 64 bits (VS 2015 and VS 2017).
@eranpeer, I'm closing some old issues, please let me know if this is ok.
