### ISSUE TITLE
Seems latest version 2.3.1 is not available on conan yet

### ISSUE THREAD

**Issue by malcolmdavey** [eranpeer/FakeIt#305]
Looking here to use Fakeit via conan. It has 2.3.0 as the latest version there.

Is there something extra that needs to be done to make 2.3.1 available?

https://conan.io/center/FakeIt?tab=overview

**Comment by FranckRJ** [comment]
It's a semi-automated process, someone need to make on PR on https://github.com/conan-io/conan-center-index and it need to be merged.

Someone wrote a bot that automatically create the commit for upgrading packages if it only require a version bump and nothing else, so you can just merge their commit: https://github.com/conan-io/conan-center-index/issues/3470
And there's a bot in the conan-center-index repo that can merge PR that only change version number, so you don't need to wait for someone's validation.

I created the PR, it should be merged soon if all the automated process works: https://github.com/conan-io/conan-center-index/pull/14777

**Comment by malcolmdavey** [comment]
Wow. Thanks.

Though I can't see fakeit in any of the lists/tables for that bot, so am not sure how to do it going forward.

**Comment by FranckRJ** [comment]
The bot only list packages that are updatables, it's not listed anymore because someone already updated the package to the latest version (2.3.2). An entry for FakeIt should appear the next time a new version is released.
