### ISSUE TITLE
Spy some dependencies

### ISSUE THREAD

**Issue by jim-king-2000** [eranpeer/FakeIt#328]
Suppose we have a function in my production code.

```C++
void ProductionCode()
{
    do1Thing();
    do2Thing();
    do3Thing();
}
```

Now we need write a unit test for this function. And we want to spy `do2Thing()` and let it throw an exception. Pseudo-code is like this:

```C++
#include "ProductionCode.h"

TEST()
{
    mock("do2Thing", [](){ throw "exception"; });
    ProductionCode();
    mock.assertThrow("exception");
}
```

Is it possible to do this without changing the source code of `ProductionCode`?

**Comment by FranckRJ** [comment]
You can only mock virtual functions. Basically the library works by creating fake objects with an hand-crafted vtable, so when calling a virtual function on that object it will call the mocked function that you defined in your test.
