### ISSUE TITLE
FakeIt failing to compile when using FetchContent

### ISSUE THREAD

**Issue by lukasrychnovsky** [eranpeer/FakeIt#346]
I am downloading the FakeIt library through fetch content
```
FetchContent_Declare(
  FakeIt
  GIT_REPOSITORY https://github.com/eranpeer/FakeIt.git
  GIT_TAG        2.4.1
  SYSTEM
)
FetchContent_MakeAvailable(FakeIt)
```
Then I am linking with a specified version as catch 
`target_link_libraries(CoreTestsCatch2 Catch2 FakeIt-<catch> VersionControlToolLib)
`
As per quickstart guide I am just including the fake it header
`#include <fakeit.hpp>
`
However I am getting 
`fatal error: fakeit.hpp: No such file or directory`

**Comment by FranckRJ** [comment]
The name of the library you should link its `FakeIt-catch`, you should not put "<>" around the name. Maybe you'll also need to put the `FakeIt::` prefix, so it'll look like `FakeIt::FakeIt-catch`, but I don't know if it's necessary.

**Comment by lukasrychnovsky** [comment]
> The name of the library you should link its `FakeIt-catch`, you should not put "<>" around the name. Maybe you'll also need to put the `FakeIt::` prefix, so it'll look like `FakeIt::FakeIt-catch`, but I don't know if it's necessary.

This fixed it, thanks
