### ISSUE TITLE
FakeIt broken with latest boost boost 1.59.0

### ISSUE THREAD

**Issue by marco-m** [eranpeer/FakeIt#38]
Latest boost 1.59.0 removed boost::test_tools::tt_detail::check_impl(), which is used by FakeIt:

```
In file included from test-broadcast.cpp:13:
src/FakeIt/single_header/boost/fakeit.hpp:1123:45: error: no member named 'check_impl' in namespace
      'boost::test_tools::tt_detail'; did you mean 'check_type'?
            ::boost::test_tools::tt_detail::check_impl(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by marco-m** [comment]
Hello! Any news/thoughts?

**Comment by eranpeer** [comment]
Hi, I did not have time to fix it yet. I hope I'll have more time by next
weekend. I'll do my best to fix this one soon.

On Wed, Sep 9, 2015 at 8:46 PM, Marco Molteni <notifications@github.com>
wrote:

> Hello! Any news/thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eranpeer/FakeIt/issues/38#issuecomment-138988292>.
>



-- 
Eran
972-52-8387550

**Comment by marco-m** [comment]
Thanks a lot Eran, I appreciate it :-) And, kudos for the elegance of FakeIt :-)

**Comment by eranpeer** [comment]
Fixed it. Should work now. please pull the latest version.
Thanks for submitting this issue and for the good feedback.
