### ISSUE TITLE
And suggestion on mocking a class inherit from std::enable_shared_from_this?

### ISSUE THREAD

**Issue by jicailiu** [eranpeer/FakeIt#61]
Hi, 

I have a project with std::enable_shared_from_this<> is quite commonly inherited by multiply classes. When I trying to mock these classes, I got error saying "Can't mock a type with multiple inheritance or with non-polymorphic base class". 

Is there any suggestion for this scenario? 

Thanks!

**Comment by eranpeer** [comment]
Currently, not. Due to the complexity of hacking the virtual table FakeIt can only handle simple inheritance hierarchies. Multiple inheritance is not supported.

**Comment by jicailiu** [comment]
Understand, just want to make sure. Thanks!
