### ISSUE TITLE
Help: Can FakeIt mock C functions?

### ISSUE THREAD

**Issue by jamespharvey20** [eranpeer/FakeIt#73]
Need to add a mock library to my unit tests.

All of my development is c++11, so I like the looks of FakeIt, but I do use the MySQL c connector.  I have database classes that use it internally, and would like to mock out the MySQL c connector library.

I'd like to avoid writing an abstract base class defining an interface to the MySQL library, with a class inheriting from it that uses the MySQL c connector, and another being a mock class.  I'd prefer to be able to mock the actual MySQL c functions, so I don't leave the derived class that uses the MySQL c connector untested, admittedly it would basically be a straight passthrough.

Can FakeIt help with this, or do I need to look for another mock library or use pre-processor or linker methods for C functions?

I looked through the examples and issues, and don't see anything showing mocking c functions, but wanted to ask before I assumed it can't do it.

**Comment by eranpeer** [comment]
FakeIt manipulates the virtual table. It can't handle c functions. Your
only option is to create a cpp abstract class and use it for mocking.

**Comment by jamespharvey20** [comment]
Thanks!
