### ISSUE TITLE
AlwaysDo - high memory usage

### ISSUE THREAD

**Issue by jansvoboda11** [eranpeer/FakeIt#76]
Hello.
I've noticed a lot of memory being allocated when using AlwaysDo in my tests. Memory usage steadily increases when a mock is used in long-running loop. You should be able to reproduce it by running the code below.
```c++
#include <standalone/fakeit.hpp>

using namespace fakeit;

struct Foo { virtual void bar() = 0; };

int main() {
  Mock<Foo> fooMock;
  When(Method(fooMock, bar)).AlwaysDo([] {  });
  Foo &foo = fooMock.get();

  while (true) { foo.bar(); }

  return 0;
}
```
Is this a bug in the library, or am I doing something wrong? Thanks for your answer.

**Comment by eranpeer** [comment]
Sure, the mock records every call. Hence the memory is expected to increase
in such a loop.

**Comment by jansvoboda11** [comment]
Yeah, I've realised that the next day, thanks for the reply.
