### ISSUE TITLE
No more releases?

### ISSUE THREAD

**Issue by estan** [eranpeer/FakeIt#81]
Hi,

I just found this project and it looks great.

Are releases still being made, or is it recommended to simply use the master branch?

Looking at the Releases page, it seems that in the past (~2015) releases were made with a few weeks or months in between, but then stopped at 2.0.2 (May 2015). And there's been 120+ commits to master since that release.

Thanks in advance for any clarification!

**Comment by eranpeer** [comment]
Simply use the latest. It is stable and contains all the latest fixes.
In times of heavy development, you may find the latest build icon in red (not passing) state. In these cases the latest build is the best option.

**Comment by estan** [comment]
@eranpeer Alright, thought so. Thanks for clarifying. Perhaps the README should be updated to recommend running from master? It currently says "Download the Latest Release and start using FakeIt now!" with a link to Releases.
