### ISSUE TITLE
Smarter matching against arguments of a function

### ISSUE THREAD

**Issue by rmtmckenzie** [eranpeer/FakeIt#9]
I've been taking a look at this framework and I find it very promising - I haven't seen much else quite like it yet.

However, one feature I feel would be very useful is the ability to specify only some of the arguments to a function, without having to put in a lambda.

For example, gmock uses a '_' to specify any, plus Ge for >=, LT for <=, etc.
So a function f(a,b) could be used with Using(_, 2) which would let 'a' be any value but specify that b must be 2. Or Using(Ge(1),2) would specify that 'a' is greater than 1 and 'b' is 2.

**Comment by rmtmckenzie** [comment]
I took a quick look at implementing this - the underlying comparison being used (std::tuple == std::tuple) supports this, but not the formation of the argument lists. 
If this is something you would consider - it might be possible to make it so that when arguments are passed in (both to the Using and to whatever is saving the values), they're wrapped with a type that supports either the type T or any<T>, GE<T>, LE<T>, etc... This would still have the same type-strictness as now.

When I was testing whether this could be done with the underlying tuple comparison, this is what I used:
```cpp
struct __
{
    template <typename T>
    friend bool operator== (const __ &, const T &) { return true; }
    template <typename T>
    friend bool operator== (const T &, const __ &) { return true; }
} static const _;

template <typename T>
struct _GE
{
    _GE(T t) : _t(t) {}
    T _t;
    friend bool operator== (const T & o1, const _GE & o2){ return o1 >= o2._t; }
    friend bool operator== (const _GE & o1, const T & o2){ return o1._t >= o2; }
};
template <typename T>
const _GE<T> GE(T t) { return _GE<T>(t); }
```

**Comment by eranpeer** [comment]
Ok, It took me a little longer than I thought. I added basic support for argument matching.
Given:
``` c++
struct SomeInterface {
   virtual int foo(int a, string s) = 0;
};
```
You can now write:
```c++
When(Method(mock,foo).Using( _ , "a")).Return(1);
When(Method(mock,foo).Using( Gt(1), _)).Return(7);
```
or:
```c++
Verify(Method(mock,foo).Using( Ne(1), _).Once();
```
Please take a look at: tests/argument_matching_tests.cpp for more details.
Enjoy!!

**Comment by eranpeer** [comment]
I updated the [Quickstart](https://github.com/eranpeer/FakeIt/wiki/Quickstart). It now contains a section about Argument Matching.
I also created a new releases (1.4.0) with all the latest changes.

Thank you for sending this feature request. Fakit is better now!

**Comment by rmtmckenzie** [comment]
Looks awesome! I'll try it out and let you know if I run into any problems. 
Thanks!
Morgan

Date: Sun, 18 Jan 2015 08:02:19 -0800
