### ISSUE TITLE
[QUESTION] Release v2.0.4

### ISSUE THREAD

**Issue by helmesjo** [eranpeer/FakeIt#94]
I'm running a few projects from Fakeit:master, which of course is not preferable with CI but currently necessary in combination with [Catch](https://github.com/philsquared/Catch).

Would a v2.0.4 be possible in current state?

**Comment by eranpeer** [comment]
Sure, I've just created 2.0.4.
You can use the release now.

**Comment by helmesjo** [comment]
Thanks!
