### ISSUE TITLE
Request: capture invocation arguments by value

### ISSUE THREAD

**Issue by j-mok** [eranpeer/FakeIt#96]
I've run into a case where a stubbed method accepts a by-ref argument which gets destroyed by the time verification kicks in. To my understanding FakeIt records the reference itself as part of invocation, not a copy of the referenced object. This is understandable as some types may be non-copyable. Still it would help a lot if there was syntax for explicitly marking a parameter as record-by-value during stubbing, to avoid situation where verification crashes because the referenced object is no longer there.

**Comment by Rogiel** [comment]
This seems related to #92 and the little reproducible test case I attached.

**Comment by j2bbayle** [comment]
I also came across the same issue, and spent a fair amount of time to trace it down to this "reference semantic" problem. Using `Do()` as a workaround for stubbing is alright but does not help much as verification is concerned, and it would be nice to have a clean way to have a value semantic for call history.

**Comment by jeduden** [comment]
I am now using do and check the parameters directly in the lambda there. clumsy. but better than not check the params at all.

**Comment by pjanowski** [comment]
Same issue, same workaround as jeduden. Would be great to fix this or add an option to verify by copy.

**Comment by estan** [comment]
I think I'm running into this as well, similar to what is described in #92 like @Rogiel mentioned, I get a crash when trying to verify sequences of calls to methods that take const ref arguments.

E.g.

```
    When(Method(loader, setFileName)).Do([](const QString &s) { qDebug() << s; });
    ...
    Verify(Method(loader, unload) + Method(loader, setFileName).Using("/no/such/file") + Method(loader, fileName)).Once();
```

Is there any workaround? Aren't a lot of people mocking methods with const ref arguments?

**Comment by jothepro** [comment]
@jeduden checking parameters directly in the lambda doesn't seem like a super tidy solution, since it mixes test-setup & verification. I ended up assigning the passed reference to a global variable in the `Do()`-lambda & verifying it afterwards:

```cpp
std::string passedValue;
When(Method((*mockedObject), mockedFunction)).Do([&passedValue](const std::string& value){
    passedValue = value;
 });
// Then afterwards assert passedValue-content, e.g:
REQUIRE(passedValue == "test");
```
Thats not a nice workaround at all, just wanted to signal to you that you're not alone out there, @estan ;)
Anyone out there with a better idea? :)

**Comment by malcolmdavey** [comment]
@jothepro Yes that seems the be the only sensible work around.

Was hoping someone had found a way to implement the copying?

**Comment by FranckRJ** [comment]
I'll centralize the discussion about this known bug in a new issue: #274
